version: '2'
services:
  grader:
    image: ta0tani/autograder02:1.0
    # command: jupyter lab --ip=0.0.0.0 --allow-root
    volumes:
      - ./workspaces:/root/devel/targets
      - ./results:/root/devel/results
      - ./work:/root/devel/autoassesmentchecker/work
        #      - main.ipynb:/root/devel/autoassesmentchecker/python/main.ipynb
    ports:
      - 8888:8888
